### ISSUE TITLE
Support using fabric mods with quilt loader (modrinth platform)

### ISSUE THREAD

**Issue by SettingDust** [ModdingX/Moonstone#7]
Since quilt support the most of fabric mod
Switching the loader for adding and back then is weird

**Comment by noeppi-noeppi** [comment]
I'm certain it does work when using CurseForge.

**Comment by SettingDust** [comment]
> I'm certain it does work when using CurseForge.我确信使用 CurseForge 时它确实有效。

Oops. I'm modrinth and quilt 1.20.1. For context
