### ISSUE TITLE
Searching will show the modpacks

### ISSUE THREAD

**Issue by SettingDust** [ModdingX/Moonstone#8]
![图片](https://github.com/ModdingX/Moonstone/assets/19922286/5c6b5971-aaa3-4a80-b346-fe03b678faa6)
Sodium Plus is a modpack

**Comment by MelanX** [comment]
It’s a mod/in the mod category: https://modrinth.com/mod/sodium-extra/
If you think it’s a modpack, please contact the author to list it as modpack, and not as mod.

**Comment by SettingDust** [comment]
> It’s a mod/in the mod category: [modrinth.com/mod/sodium-extra](https://modrinth.com/mod/sodium-extra/)

@MelanX Sodium Plus isn't Sodium Extra

**Comment by MelanX** [comment]
> > It’s a mod/in the mod category: [modrinth.com/mod/sodium-extra](https://modrinth.com/mod/sodium-extra/)
> 
> @MelanX Sodium Plus isn't Sodium Extra

Oh sorry, my bad 🤦
